<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <SourceCustomFilesMftMailboxRedisXml Include="$(MSBuildThisFileDirectory)..\content\*.xml" />
    </ItemGroup>
    <Target Name="MftMailboxRedisCopyFilesToProject" BeforeTargets="Build">
        <Copy SourceFiles="@(SourceCustomFilesMftMailboxRedisXml)"
            DestinationFolder="$(ProjectDir)\Docs" />
    </Target>
</Project>