[tool.commitizen]
name = "cz_conventional_commits"
version = "2.1.0-preview.1"
version_scheme = "semver2"
bump_message = "chore(release): bump from $current_version to $new_version [skip ci]"
annotated_tag = true
version_files = [
    "src/Directory.Build.props:Version"
]
changelog_incremental = true
changelog_merge_prerelease = true
