<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <SourceCustomFilesMftMailboxHttpXml Include="$(MSBuildThisFileDirectory)..\content\*.xml" />
    </ItemGroup>
    <Target Name="MftMailboxHttpCopyFilesToProject" BeforeTargets="Build">
        <Copy SourceFiles="@(SourceCustomFilesMftMailboxHttpXml)"
            DestinationFolder="$(ProjectDir)\Docs" />
    </Target>
</Project>