<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <SourceCustomFilesObservabilityAbstractionXml Include="$(MSBuildThisFileDirectory)..\content\*.xml" />
    </ItemGroup>
    <Target Name="ObservabilityAbstractionCopyFilesToProject" BeforeTargets="Build">
        <Copy SourceFiles="@(SourceCustomFilesObservabilityAbstractionXml)" DestinationFolder="$(ProjectDir)\Docs" />
    </Target>
</Project>