--- ORACLE --------------------
CREATE TABLE "SCHEMA"."AUTOHISTORY" (
    "ID" VARCHAR2(36) NOT NULL,
    "ROW_ID" VARCHAR2(50) NOT NULL,
    "CORRELATION_ID" VARCHAR2(100) NULL,
    "TABLE_NAME" VARCHAR2(128) NOT NULL,
    "BEFORE" VARCHAR2(4000),
    "AFTER" VARCHAR2(4000),
    "KIND" VARCHAR2(20) NOT NULL,
    "CREATED" TIMESTAMP WITH TIME ZONE NOT NULL,
	"USERNAME" VARCHAR2(36),
	"PERSIST" VARCHAR2(10),
    CONSTRAINT "PK_AUTOHISTORY_ID" PRIMARY KEY ("ID")
);
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA.AUTOHISTORY TO CTUSER;

/*--- SQL SERVER --------------------
Example: Json query
requisities: 
- SqlServer Only >= v.2017 
- DataType "nvarchar()"
https://docs.microsoft.com/en-us/sql/relational-databases/json/store-json-documents-in-sql-tables?view=sql-server-2017

SELECT 
ID, 
ROW_ID,
CORRELATION_ID,
TABLE_NAME,
BEFORE,
AFTER,
KIND,
CREATED,
USERNAME,
PERSIST
FROM SCHEMA.AUTOHISTORY
WHERE JSON_VALUE(BEFORE, '$.NUMERO_DAF') = 12345;

UPDATE SCHEMA.AUTOHISTORY
SET BEFORE = JSON_MODIFY(BEFORE, @Property, @Value)
WHERE ID = @Id;
*/

CREATE TABLE [SCHEMA].[AUTOHISTORY](
	[ID] [varchar](36) NOT NULL,
	[ROW_ID] [varchar](50) NOT NULL,
	[CORRELATION_ID] [varchar](100) NULL,
	[TABLE_NAME] [varchar](128) NOT NULL,
	[BEFORE] [nvarchar](4000),
	[AFTER] [nvarchar](4000),
	[KIND] [varchar](20) NOT NULL,
	[CREATED] [datetimeoffset](7) NOT NULL,
	[USERNAME] [varchar](36),
	[PERSIST] [varchar](10),
 CONSTRAINT [PK_AUTOHISTORY_ID] PRIMARY KEY CLUSTERED
(
	[ID] ASC
))
GO

--- DB2 -----------------------------
CREATE TABLE SCHEMA.AUTOHISTORY (
    ID CHAR(36) NOT NULL,
    ROW_ID CHAR(50) NOT NULL,
    CORRELATION_ID CHAR(100) NULL,
    TABLE_NAME CHAR(128) NOT NULL,
    BEFORE CHAR(4000),
    AFTER CHAR(4000),
    KIND CHAR(20) NOT NULL,
    CREATED TIMESTAMP WITH TIME ZONE NOT NULL,
	USERNAME CHAR(36),
	PERSIST CHAR(10),
    CONSTRAINT "PK_AUTOHISTORY_ID" PRIMARY KEY (ID)
)