<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <SourceCustomFilesMftMailboxXml Include="$(MSBuildThisFileDirectory)..\content\*.xml" />
    </ItemGroup>
    <Target Name="MftMailboxCopyFilesToProject" BeforeTargets="Build">
        <Copy SourceFiles="@(SourceCustomFilesMftMailboxXml)" DestinationFolder="$(ProjectDir)\Docs" />
    </Target>
</Project>