// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: SuppressMessage("Major Code Smell", "S3928:Parameter names used into ArgumentException constructors should match an existing one ", Justification = "O uso de 'nameof(_baseConfiguration)' é correto para identificar o campo sendo validado. O SonarQube não reconhece adequadamente o padrão nameof() com campos privados em contextos de validação.", Scope = "member", Target = "~M:Nuuvify.CommonPack.AzureServiceBus.Services.ServiceBusConfigurationManager.ValidateBaseConfiguration")]

// Supressões para warnings CA1031 em métodos de exemplo
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Método de exemplo demonstra tratamento de exceções genéricas para fins educacionais e logging. Em exemplos é apropriado mostrar captura de Exception para demonstrar diferentes cenários de erro.", Scope = "member", Target = "~M:Nuuvify.CommonPack.AzureServiceBus.Examples.ServiceBusUsageExamples.ExemploComTratamentoErro")]

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Método de exemplo que demonstra cenários de performance com ReuseConnections. A captura de Exception genérica é intencional para mostrar tratamento robusto em loops de processamento e evitar falha completa do exemplo.", Scope = "member", Target = "~M:Nuuvify.CommonPack.AzureServiceBus.Examples.ServiceBusUsageExamples.ExemploReuseConnections(System.Threading.CancellationToken)")]

// Supressões para métodos Dispose da classe ServiceBusMessageSender
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "No método DisposeAsync, a captura de Exception genérica é necessária para garantir que o dispose de clientes em cache não falhe silenciosamente. É crítico que o dispose sempre complete, mesmo se algum cliente específico falhar ao ser liberado. O log de warning garante visibilidade de problemas.", Scope = "member", Target = "~M:Nuuvify.CommonPack.AzureServiceBus.Services.ServiceBusMessageSender.DisposeAsync~System.Threading.Tasks.ValueTask")]

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "No método DisposeAsync principal, a captura de Exception genérica é necessária para garantir que o objeto seja marcado como disposed mesmo se houver falha na liberação de recursos. Isso evita vazamentos de memória e estados inconsistentes. O log de erro garante que problemas sejam registrados para diagnóstico.", Scope = "member", Target = "~M:Nuuvify.CommonPack.AzureServiceBus.Services.ServiceBusMessageSender.DisposeAsync~System.Threading.Tasks.ValueTask")]

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "No método Dispose protegido, a captura de Exception genérica é necessária para garantir que o padrão Dispose seja implementado corretamente. O método deve sempre marcar o objeto como disposed, mesmo se houver falha na liberação de recursos nativos. Isso segue as melhores práticas do padrão Dispose do .NET.", Scope = "member", Target = "~M:Nuuvify.CommonPack.AzureServiceBus.Services.ServiceBusMessageSender.Dispose(System.Boolean)")]

// Supressões para métodos de processamento da classe ServiceBusMessageReceiver
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "No método StartProcessingAsync, a captura de Exception genérica é necessária para garantir que o estado '_isProcessing' seja restaurado para false em qualquer cenário de falha durante inicialização. Isso evita que o objeto fique em estado inconsistente e permite tentativas futuras de processamento.", Scope = "member", Target = "~M:Nuuvify.CommonPack.AzureServiceBus.Services.Receiver.ServiceBusMessageReceiver`1.StartProcessingAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "No método StopProcessingAsync, a captura de Exception genérica é necessária para garantir tratamento robusto de qualquer falha durante a parada do processamento. O método deve sempre tentar parar o processamento e garantir que o estado seja consistente, independentemente de falhas específicas no Service Bus.", Scope = "member", Target = "~M:Nuuvify.CommonPack.AzureServiceBus.Services.Receiver.ServiceBusMessageReceiver`1.StopProcessingAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "No método HandleMessageAsync, a captura de Exception genérica é o último nível de tratamento para exceções não previstas. É crítico que qualquer falha não tratada seja capturada, registrada e direcionada para Dead Letter Queue, evitando perda de mensagens e garantindo observabilidade total do processamento.", Scope = "member", Target = "~M:Nuuvify.CommonPack.AzureServiceBus.Services.Receiver.ServiceBusMessageReceiver`1.HandleMessageAsync(Azure.Messaging.ServiceBus.ProcessMessageEventArgs,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]

// Supressões para regra S2325 - Properties que não podem ser static
[assembly: SuppressMessage("Major Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "As propriedades RequestConfiguration, Logger e ConfigurationCustom não podem ser static pois são injetadas via Dependency Injection e são específicas por instância. RequestConfiguration contém CorrelationId único, Logger é específico por tipo genérico T, e ConfigurationCustom pode variar por instância.", Scope = "member", Target = "~P:Nuuvify.CommonPack.AzureServiceBus.Services.Receiver.ServiceBusMessageReceiver`1.RequestConfiguration")]

[assembly: SuppressMessage("Major Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "As propriedades RequestConfiguration, Logger e ConfigurationCustom não podem ser static pois são injetadas via Dependency Injection e são específicas por instância. RequestConfiguration contém CorrelationId único, Logger é específico por tipo genérico T, e ConfigurationCustom pode variar por instância.", Scope = "member", Target = "~P:Nuuvify.CommonPack.AzureServiceBus.Services.Receiver.ServiceBusMessageReceiver`1.Logger")]

[assembly: SuppressMessage("Major Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "As propriedades RequestConfiguration, Logger e ConfigurationCustom não podem ser static pois são injetadas via Dependency Injection e são específicas por instância. RequestConfiguration contém CorrelationId único, Logger é específico por tipo genérico T, e ConfigurationCustom pode variar por instância.", Scope = "member", Target = "~P:Nuuvify.CommonPack.AzureServiceBus.Services.Receiver.ServiceBusMessageReceiver`1.ConfigurationCustom")]
